#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
/* generated by tools/make-callentries.R */
SEXP GdalPtrDataset();
SEXP GdalPtrGDALOpen(SEXP dataset_xptr, SEXP dsn_name_sexp);
SEXP GdalPtrGetRasterSize(SEXP dataset_xptr);
SEXP GdalPtrVSIReadDirRecursive(SEXP dsn_name_sexp);
SEXP GdalPtrGDALVersionInfo();
static const R_CallMethodDef CallEntries[] = {
    {"GdalPtrDataset", (DL_FUNC)&GdalPtrDataset, 0},
    {"GdalPtrGDALOpen", (DL_FUNC)&GdalPtrGDALOpen, 2},
    {"GdalPtrGetRasterSize", (DL_FUNC)&GdalPtrGetRasterSize, 1},
    {"GdalPtrVSIReadDirRecursive", (DL_FUNC)&GdalPtrVSIReadDirRecursive, 1},
    {"GdalPtrGDALVersionInfo", (DL_FUNC)&GdalPtrGDALVersionInfo, 0},
    {NULL, NULL, 0}};
/* end generated by tools/make-callentries.R */


void R_init_gdalptr(DllInfo* dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
