# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Open a gdal dataset
#'
#' @param dsn data source name (file path, url,etc)
#' @param sds subdataset to choose (1-based, or defaults to 1 if not specified or if there are no sds)
#' @return external pointer
#' @export
xptr_GDALOpen <- function(dsn, sds = as.integer( c(0))) {
    .Call(`_gdalptr_xptr_GDALOpen`, dsn, sds)
}

#' Query the raster size a gdal dataset 
#'
#' @param xp external pointer returned by [xptr_GDALOpen()]
#' @return ncol, nrow of underlying data set
#' @export
xptr_GDALGetRasterSize <- function(xp) {
    .Call(`_gdalptr_xptr_GDALGetRasterSize`, xp)
}

